### ISSUE TITLE
ns-train splatfacto

### ISSUE THREAD

**Issue by eekshithad** [nerfstudio-project/nerfstudio#3765]
i am trying to build 3d gaussian splat using nerfstudio, but when trying to train on my dataset i am facing repeated errors.
i am working with python v3.10, cuda toolkit v11.8, PyTorch v2.4.1, MSVC v14.39

until now when i did python -c "from gsplat.cuda import _backend" i have got Importerror: cannot import name 'csrc' and runtime errors too which made ninja commands running failed.

but later when i did pip install nerfacc things work fine.
later python -c "from gsplat.cuda import _backend" command didn't show me any error. but then later when i try to train on my dataset again the same error- importerror, runtime error are raising.

how can i solve this issue, i need my installation to be successful, it would be great if any one validate my setup.

**Comment by jannick-schroeer** [comment]
I think the ninja error is leading to the erros later down the pipeline. Would be helpfull if you could send this error. I would guess that your `gcc` and `g++` are not compatible with building. Try using `gcc` and `g++` version 10. You can after building switch back to any version you like.
