### ISSUE TITLE
cannot import name 'jacrev' from 'functorch'

### ISSUE THREAD

**Issue by herrpedro** [nerfstudio-project/nerfstudio#1167]
hi all

i'm running python 3.10.9
gpu 1060 6gb
windows 
i9 32gb

followed the installation guide at https://docs.nerf.studio/en/latest/quickstart/installation.html
when i try to train the first scene i get 

T:\nerf>ns-train nerfacto --data temp/capuchos
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\Scripts\ns-train.exe\__main__.py", line 4, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\scripts\train.py", line 50, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\nerfstudio\configs\method_configs.py", line 48, in <module>
    from nerfstudio.models.mipnerf import MipNerfModel
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\nerfstudio\models\mipnerf.py", line 31, in <module>
    from nerfstudio.fields.vanilla_nerf_field import NeRFField
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\nerfstudio\fields\vanilla_nerf_field.py", line 33, in <module>
    from nerfstudio.field_components.spatial_distortions import SpatialDistortion
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\nerfstudio\field_components\spatial_distortions.py", line 20, in <module>
    from functorch import jacrev, vmap
ImportError: cannot import name 'jacrev' from 'functorch' (unknown location)

don't know what else can i provide to help you assist me. just ask.
happy holidays and thank you

**Comment by tancik** [comment]
I ran into this issue when updating pytorch to 1.13. If using pytorch > 1.12 you will need to first uninstall functorch `pip uninstall functorch`, then reinstall pytorch.

**Comment by kenchen3000** [comment]
I have the same error on windows: 
  File "C:\gitcode\nerfstudio\nerfstudio\field_components\spatial_distortions.py", line 20, in <module>
    from functorch import jacrev, vmap
ImportError: cannot import name 'jacrev' from 'functorch' (unknown location)

I tried "uninstall functorch pip uninstall functorch, then reinstall pytorch. " but it doesn't fix the problem. would appreciate any helps. thanks.
