### ISSUE TITLE
ImportError: cannot import name 'ForwardRef' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)

### ISSUE THREAD

**Issue by ichsan2895** [nerfstudio-project/nerfstudio#3050]
**Describe the bug**
Import error in `ns-train splatfacto`

**To Reproduce**
1. Install the latest version
```
# make sure you uninstall the previous gsplat and nerfstudio
pip uninstall gsplat nerfstudio -y

# install it from pip
pip install git+https://github.com/nerfstudio-project/gsplat.git@v0.1.10
pip install git+https://github.com/nerfstudio-project/nerfstudio.git@v1.0.3
```

2. Run this command
``` 
ns-train splatfacto --logging.steps-per-log 200 --vis viewer+wandb --viewer.websocket-port 7007 \
    --pipeline.model.resolution-schedule 3000 \
    --pipeline.model.num-downscales 2 \
    nerfstudio-data \
    --data path/to/scene --downscale-factor 1
```
3. Error message:
```
Traceback (most recent call last):
  File "/usr/local/bin/ns-train", line 5, in <module>
    from nerfstudio.scripts.train import entrypoint
  File "/usr/local/lib/python3.10/dist-packages/nerfstudio/scripts/train.py", line 58, in <module>
    import tyro
  File "/usr/local/lib/python3.10/dist-packages/tyro/__init__.py", line 3, in <module>
    from . import conf as conf
  File "/usr/local/lib/python3.10/dist-packages/tyro/conf/__init__.py", line 11, in <module>
    from ._confstruct import arg as arg
  File "/usr/local/lib/python3.10/dist-packages/tyro/conf/_confstruct.py", line 4, in <module>
    from .._fields import MISSING_NONPROP
  File "/usr/local/lib/python3.10/dist-packages/tyro/_fields.py", line 45, in <module>
    from . import (
  File "/usr/local/lib/python3.10/dist-packages/tyro/_docstrings.py", line 15, in <module>
    from . import _resolver, _strings, _unsafe_cache
  File "/usr/local/lib/python3.10/dist-packages/tyro/_resolver.py", line 25, in <module>
    from typing_extensions import (
ImportError: cannot import name 'ForwardRef' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)
```
**Expected behavior**
Runs training smoothly without problem

**How to solve it**
Revert back to previous version
```
pip uninstall nerfstudio gsplat -y
pip install git+https://github.com/nerfstudio-project/gsplat.git@v0.1.8
pip install git+https://github.com/nerfstudio-project/nerfstudio.git@ae6c46cfeaebbe28f9cd48fa986755e27b5f0ae2
```

**Additional context**
Python 3.10
Pytorch 2.0.1+cu118
Ubuntu 22.04 LTS
typing_extensions 4.40.0
tyro 0.8.1

**Comment by brentyi** [comment]
Thanks for reporting! It looks like this is from an old version of `typing_extensions`: if you `pip install --upgrade typing_extensions` the error should go away.

I can fix this by bumping the minimum `typing_extensions` version in `tyro`.

**Comment by ichsan2895** [comment]
> Thanks for reporting! It looks like this is from an old version of `typing_extensions`: if you `pip install --upgrade typing_extensions` the error should go away.
> 
> I can fix this by bumping the minimum `typing_extensions` version in `tyro`.

Here is my experiment
the version which works with nerfstudio v1.0.2 and gsplat 0.1.8 => tyro 0.7.3
the version which do Not works with nerfstudio v1.0.3 and gsplat 0.1.10 => tyro 0.8.1

**Comment by brentyi** [comment]
Yeah, the problem is because I import `typing_extensions.ForwardRef` in `tyro>=0.8.0`, but that's only available in `typing_extensions>=4.7.0` (from November 2023). We were requiring `typing_extensions>=4.3.0` (from July 2022).

I just pushed version `0.8.2` of `tyro`, which will have this fixed.

**Comment by ichsan2895** [comment]
This solved my problem
```
pip install tyro==0.8.2 typing-extensions==4.11.0
```
