### ISSUE TITLE
Training with semantic-nerfw is broken after #750 commit.

### ISSUE THREAD

**Issue by vahidEttehadi** [nerfstudio-project/nerfstudio#821]
I cannot run "ns-train semantic-nerfw friends-data --data data/friends/Friends-monica_apartment" after v0.1.3 commit. it shows the below error:

  File "/mnt/07b9581f-566a-42d8-9478-9d2e5fd40e78/Projects/nerfstudio/nerfstudio/models/semantic_nerfw.py", line 107, in populate_modules
    for _ in range(self.config.num_proposal_network_iterations):
AttributeError: 'SemanticNerfWModelConfig' object has no attribute 'num_proposal_network_iterations'

**Comment by kevinddchen** [comment]
This should be fixed with #838. Please re-open if you still have this issue.
